class ManageIndici < ActiveRecord::Migration
  def self.up
    
    execute "DROP INDEX IF EXISTS FATTURE_CLIENTI_IDX"
    execute "CREATE INDEX FC_CLIENTE_FK_IDX ON FATTURE_CLIENTI (cliente_id)"
    execute "CREATE INDEX FC_NUM_IDX ON FATTURE_CLIENTI (num)"
    execute "CREATE INDEX FC_DATA_EMISSIONE_IDX ON FATTURE_CLIENTI (data_emissione)"

    execute "DROP INDEX IF EXISTS FATTURE_FORNITORI_IDX"
    execute "CREATE INDEX FF_FORNITORE_FK_IDX ON FATTURE_FORNITORI (fornitore_id)"
    execute "CREATE INDEX FF_NUM_IDX ON FATTURE_FORNITORI (num)"
    execute "CREATE INDEX FF_DATA_EMISSIONE_IDX ON FATTURE_FORNITORI (data_emissione)"

    execute "DROP INDEX IF EXISTS NOTA_SPESE_IDX"
    execute "CREATE INDEX NS_NUM_IDX ON NOTA_SPESE (num)"
    execute "CREATE INDEX NS_DATA_EMISSIONE_IDX ON NOTA_SPESE (data_emissione)"

    execute "DROP INDEX IF EXISTS PAGAMENTI_FATTURE_CLIENTI_IDX"
    execute "CREATE INDEX PFC_FATTURA_CLIENTE_FK_IDX ON PAGAMENTI_FATTURE_CLIENTI (fattura_cliente_id)"
    execute "CREATE INDEX PFC_MAXI_PAGAMENTO_CLIENTE_FK_IDX ON PAGAMENTI_FATTURE_CLIENTI (maxi_pagamento_cliente_id)"
    execute "CREATE INDEX PFC_TIPO_PAGAMENTO_FK_IDX ON PAGAMENTI_FATTURE_CLIENTI (tipo_pagamento_id)"
    execute "CREATE INDEX PFC_BANCA_FK_IDX ON PAGAMENTI_FATTURE_CLIENTI (banca_id)"
    execute "CREATE INDEX PFC_DATA_PAGAMENTO_FK_IDX ON PAGAMENTI_FATTURE_CLIENTI (data_pagamento)"
    execute "CREATE INDEX PFC_DATA_REGISTRAZIONE_FK_IDX ON PAGAMENTI_FATTURE_CLIENTI (data_registrazione)"

    execute "DROP INDEX IF EXISTS PAGAMENTI_FATTURE_FORNITORI_IDX"
    execute "CREATE INDEX PFF_FATTURA_FORNITORE_FK_IDX ON PAGAMENTI_FATTURE_FORNITORI (fattura_fornitore_id)"
    execute "CREATE INDEX PFF_MAXI_PAGAMENTO_FORNITORE_FK_IDX ON PAGAMENTI_FATTURE_FORNITORI (maxi_pagamento_fornitore_id)"
    execute "CREATE INDEX PFF_TIPO_PAGAMENTO_FK_IDX ON PAGAMENTI_FATTURE_FORNITORI (tipo_pagamento_id)"
    execute "CREATE INDEX PFF_BANCA_FK_IDX ON PAGAMENTI_FATTURE_FORNITORI (banca_id)"
    execute "CREATE INDEX PFF_DATA_PAGAMENTO_FK_IDX ON PAGAMENTI_FATTURE_FORNITORI (data_pagamento)"
    execute "CREATE INDEX PFF_DATA_REGISTRAZIONE_FK_IDX ON PAGAMENTI_FATTURE_FORNITORI (data_registrazione)"

    execute "DROP INDEX IF EXISTS RIGHE_NOTA_SPESE_IDX"
    execute "CREATE INDEX RNS_NOTA_SPESE_FK_IDX ON RIGHE_NOTA_SPESE (nota_spese_id)"

    execute "DROP INDEX IF EXISTS MAXI_PAGAMENTI_CLIENTI_IDX"
    execute "CREATE INDEX MPC_AZIENDA_FK_IDX ON MAXI_PAGAMENTI_CLIENTI (azienda_id)"
    execute "CREATE INDEX MPC_TIPO_PAGAMENTO_FK_IDX ON MAXI_PAGAMENTI_CLIENTI (tipo_pagamento_id)"
    execute "CREATE INDEX MPC_BANCA_FK_IDX ON MAXI_PAGAMENTI_CLIENTI (banca_id)"
    execute "CREATE INDEX MPC_DATA_PAGAMENTO_FK_IDX ON MAXI_PAGAMENTI_CLIENTI (data_pagamento)"
    execute "CREATE INDEX MPC_DATA_REGISTRAZIONE_FK_IDX ON MAXI_PAGAMENTI_CLIENTI (data_registrazione)"

    execute "DROP INDEX IF EXISTS MAXI_PAGAMENTI_FORNITORI_IDX"
    execute "CREATE INDEX MPF_AZIENDA_FK_IDX ON MAXI_PAGAMENTI_FORNITORI (azienda_id)"
    execute "CREATE INDEX MPF_TIPO_PAGAMENTO_FK_IDX ON MAXI_PAGAMENTI_FORNITORI (tipo_pagamento_id)"
    execute "CREATE INDEX MPF_BANCA_FK_IDX ON MAXI_PAGAMENTI_FORNITORI (banca_id)"
    execute "CREATE INDEX MPF_DATA_PAGAMENTO_IDX ON MAXI_PAGAMENTI_FORNITORI (data_pagamento)"
    execute "CREATE INDEX MPF_DATA_REGISTRAZIONE_IDX ON MAXI_PAGAMENTI_FORNITORI (data_registrazione)"

    execute "DROP INDEX IF EXISTS PRIMA_NOTA_DATA_RESIDUO_IDX"
    execute "DROP INDEX IF EXISTS PRIMA_NOTA_IDX"
    execute "CREATE INDEX PN_AZIENDA_FK_IDX ON PRIMA_NOTA (azienda_id)"
    execute "CREATE INDEX PN_CAUSALE_FK_IDX ON PRIMA_NOTA (causale_id)"
    execute "CREATE INDEX PN_BANCA_FK_IDX ON PRIMA_NOTA (banca_id)"
    execute "CREATE INDEX PN_DATA_OPERAZIONE_IDX ON PRIMA_NOTA (data_operazione)"
    execute "CREATE INDEX PN_DATA_REGISTRAZIONE_IDX ON PRIMA_NOTA (data_registrazione)"
    execute "CREATE INDEX PN_PARENT_FK_IDX ON PRIMA_NOTA (parent_id)"
    
    execute "DROP INDEX IF EXISTS PAGAMENTI_PRIMA_NOTA_IDX1"
    execute "DROP INDEX IF EXISTS PAGAMENTI_PRIMA_NOTA_IDX2"
    execute "DROP INDEX IF EXISTS PAGAMENTI_PRIMA_NOTA_IDX3"
    execute "CREATE INDEX PPN_PRIMA_NOTA_FK_IDX ON PAGAMENTI_PRIMA_NOTA (prima_nota_id)"
    execute "CREATE INDEX PPN_PAGAMENTO_FATTURA_CLIENTE_FK_IDX ON PAGAMENTI_PRIMA_NOTA (pagamento_fattura_cliente_id)"
    execute "CREATE INDEX PPN_PAGAMENTO_FATTURA_FORNITORE_FK_IDX ON PAGAMENTI_PRIMA_NOTA (pagamento_fattura_fornitore_id)"
    execute "CREATE INDEX PPN_MAXI_PAGAMENTO_CLIENTE_FK_IDX ON PAGAMENTI_PRIMA_NOTA (maxi_pagamento_cliente_id)"
    execute "CREATE INDEX PPN_MAXI_PAGAMENTO_FORNITORE_FK_IDX ON PAGAMENTI_PRIMA_NOTA (maxi_pagamento_fornitore_id)"
    
  end

  def self.down

  end
end
